help:
	python3.8 interpret.py --help
parse_only:
	php8.1 test.php --directory=tests/parse_only --recursive --jexamxml=test_lib/jexamxml/jexamxml.jar --parse-only > index.html
int_only:
	php8.1 test.php --directory=tests/int_only --recursive --jexamxml=test_lib/jexamxml/jexamxml.jar --int-only > index.html
test:
	php8.1 test.php --directory=tests/both --recursive --jexamxml=test_lib/jexamxml/jexamxml.jar > index.html
